# This is a basic workflow to help you get started with Actions
name: Deployment Base - deploy

on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy-base:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Caching
        uses: actions/cache@v3
        id: my-cache
        with:
          path: my_new_file
          key: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Checking cache
        if: steps.my-cache.outputs.cache-hit == 'true'
        run: echo  SE ENCONTRÓ CACHE

      # Runs a single command using the runners shell
      - name: Kubernete deploy
        run: echo kubectl apply .........